# Generated by Django 5.2.1 on 2025-08-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="is_featured",
            field=models.BooleanField(default=False, verbose_name="Is Featured"),
        ),
    ]
