# Generated by Django 5.2.1 on 2025-08-15 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_session_is_featured"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eventfavorite",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Event Favorite",
                "verbose_name_plural": "Event Favorites",
            },
        ),
        migrations.AlterModelOptions(
            name="eventview",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Event View",
                "verbose_name_plural": "Event Views",
            },
        ),
        migrations.RemoveIndex(
            model_name="eventattachment",
            name="events_even_type_9e3f86_idx",
        ),
        migrations.RemoveIndex(
            model_name="eventattachment",
            name="events_even_created_ea34f7_idx",
        ),
        migrations.RemoveIndex(
            model_name="eventmoderationlog",
            name="events_even_event_i_ff5013_idx",
        ),
        migrations.RemoveIndex(
            model_name="eventmoderationlog",
            name="events_even_moderat_d008c4_idx",
        ),
        migrations.RemoveIndex(
            model_name="eventmoderationlog",
            name="events_even_action_616529_idx",
        ),
        migrations.RemoveIndex(
            model_name="eventview",
            name="events_even_event_i_550a40_idx",
        ),
        migrations.RemoveIndex(
            model_name="eventview",
            name="events_even_user_id_e60377_idx",
        ),
        migrations.AddField(
            model_name="eventattachment",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="events.event",
                verbose_name="Event",
            ),
        ),
        migrations.AddField(
            model_name="eventattachment",
            name="exhibitor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="events.exhibitor",
                verbose_name="Exhibitor",
            ),
        ),
        migrations.AddField(
            model_name="eventattachment",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="events.product",
                verbose_name="Product",
            ),
        ),
        migrations.AddField(
            model_name="eventattachment",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="events.session",
                verbose_name="Session",
            ),
        ),
        migrations.AddIndex(
            model_name="eventattachment",
            index=models.Index(
                fields=["type", "created_at"], name="events_even_type_4169a2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventattachment",
            index=models.Index(
                fields=["event", "type"], name="events_even_event_i_c419a6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventattachment",
            index=models.Index(
                fields=["session", "type"], name="events_even_session_fb72dd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventmoderationlog",
            index=models.Index(
                fields=["event", "action"], name="events_even_event_i_7dd33b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventmoderationlog",
            index=models.Index(
                fields=["moderator", "created_at"],
                name="events_even_moderat_8fd1c5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="eventmoderationlog",
            index=models.Index(
                fields=["action", "created_at"], name="events_even_action_af3a37_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventview",
            index=models.Index(
                fields=["event", "-created_at"], name="events_even_event_i_0d408f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="eventview",
            index=models.Index(
                fields=["user", "-created_at"], name="events_even_user_id_43cd0b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="eventattachment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("event__isnull", False),
                        ("session__isnull", True),
                        ("exhibitor__isnull", True),
                        ("product__isnull", True),
                    ),
                    models.Q(
                        ("event__isnull", True),
                        ("session__isnull", False),
                        ("exhibitor__isnull", True),
                        ("product__isnull", True),
                    ),
                    models.Q(
                        ("event__isnull", True),
                        ("session__isnull", True),
                        ("exhibitor__isnull", False),
                        ("product__isnull", True),
                    ),
                    models.Q(
                        ("event__isnull", True),
                        ("session__isnull", True),
                        ("exhibitor__isnull", True),
                        ("product__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="attachment_single_relation",
            ),
        ),
    ]
