# Generated by Django 5.2.1 on 2025-08-14 18:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="bio",
            field=models.TextField(
                blank=True,
                help_text="Brief description about yourself",
                max_length=500,
                verbose_name="bio",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="current_position",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="current position"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True, verbose_name="date of birth"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="industry",
            field=models.CharField(blank=True, max_length=100, verbose_name="industry"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="location",
            field=models.CharField(blank=True, max_length=100, verbose_name="location"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="phone",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="phone number"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="profile_pictures/",
                verbose_name="profile picture",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="show_email",
            field=models.BooleanField(
                default=True,
                help_text="Show email address in profile",
                verbose_name="show email",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="show_phone",
            field=models.BooleanField(
                default=True,
                help_text="Show phone number in profile",
                verbose_name="show phone",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("private", "Private"),
                    ("connections-only", "Connections Only"),
                ],
                default="public",
                help_text="Alias for profile_visibility",
                max_length=20,
                verbose_name="visibility",
            ),
        ),
    ]
