# Generated by Django 5.2.1 on 2025-08-23 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_userprofile_bio_userprofile_current_position_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitylog",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("profile_update", "Profile Update"),
                    ("connection_request", "Connection Request"),
                    ("connection_accept", "Connection Accept"),
                    ("endorsement", "Endorsement"),
                    ("project_update", "Project Update"),
                    ("skill_update", "Skill Update"),
                    ("login", "Login"),
                    ("password_change", "Password Change"),
                    ("profile_view", "Profile View"),
                    ("resume_created", "Resume Created"),
                    ("resume_updated", "Resume Updated"),
                    ("resume_deleted", "Resume Deleted"),
                    ("resume_published", "Resume Published"),
                    ("resume_downloaded", "Resume Downloaded"),
                    ("resume_generated", "Resume Generated"),
                    ("recommendation_given", "Recommendation Given"),
                    ("recommendation_received", "Recommendation Received"),
                    ("recommendation_updated", "Recommendation Updated"),
                    ("recommendation_deleted", "Recommendation Deleted"),
                    ("recommendation_approved", "Recommendation Approved"),
                    ("recommendation_declined", "Recommendation Declined"),
                    ("recommendation_requested", "Recommendation Requested"),
                    ("login_failed", "Login Failed"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="experience",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="experience",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
