# Generated by Django 5.2.1 on 2025-05-16 06:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit_log", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="priority",
            field=models.CharField(
                choices=[("LOW", "Low"), ("MED", "Medium"), ("HIGH", "High")],
                default="LOW",
                help_text="Priority level of the action.",
                max_length=10,
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["priority"], name="audit_log_a_priorit_cdd9ea_idx"
            ),
        ),
    ]
