# Generated by Django 5.2.1 on 2025-08-14 21:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chats", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="delete_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("for_me", "Delete for me"),
                    ("for_everyone", "Delete for everyone"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="status",
            field=models.CharField(
                choices=[
                    ("sending", "Sending"),
                    ("sent", "Sent"),
                    ("received", "Received"),
                    ("read", "Read"),
                    ("edited", "Edited"),
                    ("deleted", "Deleted"),
                    ("failed", "Failed"),
                    ("scheduled", "Scheduled"),
                ],
                default="sending",
                max_length=20,
            ),
        ),
    ]
