# Generated by Django 5.2.1 on 2025-08-14 21:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chats", "0002_chatmessage_delete_type_alter_chatmessage_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatattachment",
            name="checksum",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="chatattachment",
            name="download_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
