# Generated by Django 5.2.1 on 2025-08-14 21:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chats", "0003_chatattachment_checksum_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="mentions",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
