# Generated by Django 5.2.1 on 2025-08-15 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chats", "0004_chatmessage_mentions"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatpoll",
            name="chat",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polls",
                to="chats.chat",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="chat",
            name="last_message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="chats.chatmessage",
            ),
        ),
        migrations.AlterField(
            model_name="chatcall",
            name="status",
            field=models.CharField(
                choices=[
                    ("ringing", "Ringing"),
                    ("ongoing", "Ongoing"),
                    ("active", "Active"),
                    ("ended", "Ended"),
                    ("missed", "Missed"),
                    ("declined", "Declined"),
                    ("failed", "Failed"),
                ],
                default="ringing",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="chatpoll",
            name="message",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="poll",
                to="chats.chatmessage",
            ),
        ),
    ]
